### PR TITLE
feat(useQuery): Combine GraphQL errors in single ApolloError.

### LINKED ISSUE #34: ApolloQueryResult type with wrong property
In ApolloQueryResult type property errors should be singular just an error.

export declare type ApolloQueryResult<T> = {
  data: T;
  error?: GraphQLError[];      //Changed
  loading: boolean;
  networkStatus: NetworkStatus;
  stale: boolean;
};

### PR DESCRIPTION
**Pull request by umidbekkarimov**
Implementation adopted from react Apollos [Query](https://github.com/apollographql/react-apollo/blob/62de2074fe01cde5d21dbfc582c5bb87c2011a36/src/Query.tsx#L389-L395). ~~Because of #28 already is a breaking change, I decided to remove `errors`.~~
Closes #34.

### CODE REVIEW

**Comment by umidbekkarimov** [comment]
@trojanowski I rolled back breaking change, pls review this.

**Comment by trojanowski** [comment]
@umidbekkarimov I think you forgot to push a commit with rolled back breaking changes :)

**Comment by umidbekkarimov** [comment]
@trojanowski yup 😅

**Comment by trojanowski** [comment]
Wow, you're really fast :)

**Comment by umidbekkarimov** [comment]
@trojanowski extra active day because of React release :)

**Pull request merged**
